INSERT INTO users (user_id, name, email, role)
VALUES (1, 'User1', 'user1@example.com', 'WORKER'),
       (2, 'User2', 'user2@example.com', 'WORKER'),
       (3, 'User3', 'user3@example.com', 'WORKER'),
       (4, 'User4', 'user4@example.com', 'WORKER'),
       (5, 'User5', 'user5@example.com', 'WORKER'),
       (6, 'User6', 'user6@example.com', 'WORKER'),
       (7, 'User7', 'user7@example.com', 'WORKER'),
       (8, 'User8', 'user8@example.com', 'WORKER'),
       (9, 'User9', 'user9@example.com', 'WORKER'),
       (10, 'User10', 'user10@example.com', 'WORKER'),
       (11, 'User11', 'user11@example.com', 'WORKER'),
       (12, 'User12', 'user12@example.com', 'WORKER'),
       (13, 'User13', 'user13@example.com', 'WORKER'),
       (14, 'User14', 'user14@example.com', 'WORKER'),
       (15, 'User15', 'user15@example.com', 'WORKER'),
       (16, 'User16', 'user16@example.com', 'WORKER'),
       (17, 'User17', 'user17@example.com', 'WORKER'),
       (18, 'User18', 'user18@example.com', 'WORKER'),
       (19, 'User19', 'user19@example.com', 'WORKER'),
       (20, 'User20', 'user20@example.com', 'WORKER');